import React from "react";
import Head from "next/head";
import styles from "../styles/Android.module.scss";
import Link from "next/link";

export default function Android() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Android</title>
        <meta name="Android program details" content="Generated by datum" />
      </Head>
      <main>
        <h1 className={styles.title}>
          <span>Android Program</span>
        </h1>
        <p></p>

        <div className={styles.body_borders}>
          <div className={styles.main_container}>
            <p>
              In this program you will learn android programming concepts and
              build a variety of apps, using the Java programming language. You
              will start with Hello, World app and work your way up to apps that
              schedule jobs, update settings and use android architecture
              components.
            </p>
          </div>

          <div className={styles.rules_section}>
            <p className={styles.rules}>
              <strong>Program overview</strong>
            </p>
            <ul>
              <li>2 months timeline.</li>
              <li>submit 8 different android projects.</li>
              <li>expected 10 to 16 weekly hours.</li>
              <li>attending weekly coaching sessions.</li>
              <li>attending weekly support sessions.</li>
              <li>cost 1500 SAR</li>
            </ul>
          </div>

          <div className={styles.rules_section}>
            <p className={styles.rules}>
              <strong>We don't just coach, we also give gifts</strong>
            </p>
            <ul>
              <li>50% refund for all the graduates.</li>
              <li>100% refund for the person who gets highest score.</li>
              <li>There is google certificate coupon for the second person.</li>
              <li>
                6 months subscription to our communication channel for all the
                graduates.
              </li>
            </ul>
          </div>

          <div className={styles.rules_section}>
            <p className={styles.rules}>
              <strong>Registration</strong>
            </p>
            <ul>
              <li>You need to pass a simple programming assessment in Java.</li>
            </ul>
          </div>

          <div className={styles.rules_section}>
            <p className={styles.rules}>
              <strong>How to graduate?</strong>
            </p>
            <ul>
              <li>
                You need to complete all the projects before the end of the
                program.
              </li>
            </ul>
          </div>

          <div className={styles.bottom_grid}>
            <Link href="/registration">
              <a className={styles.reg_btn}>
                <p> Willing to join? </p>
              </a>
            </Link>

            <Link href="/">
              <a className={styles.reg_btn}>
                <p> Back </p>
              </a>
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
